[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'nvim-lua/completion-nvim'

###
# utility
###
[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap [NERDTree] <Nop>
  nmap <Space>n [NERDTree]
  nnoremap <silent> [NERDTree] :<C-u>NERDTreeToggle<CR>
'''

###
# display
###
[[plugins]]
repo = 'KeitaNakamura/highlighter.nvim'
hook_add = '''
  let g:highlighter#auto_update = 1
  let g:heghlighter#project_root_signs = ['.git', '.clang-format']
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
  let g:indent_guides_enable_on_vim_startup = 1
  let g:indent_guides_exclude_filetypes = ['markdown']

  let g:indent_guides_auto_colors = 1
  "augroup set_indent_guides
  "  autocmd!
  "  autocmd VimEnter,colorscheme * :hi IndentGuidesOdd  guifg=gray guibg=#393939 ctermfg=8 ctermbg=7
  "  autocmd VimEnter,colorscheme * :hi IndentGuidesEven guifg=gray guibg=#303030 ctermfg=7 ctermbg=8
  "augroup END
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

###
# browser
###
repo = 'tyru/open-browser.vim'
hook_add = '''
  let g:netrw_nogx = 1 " disable netrw's gx mapping.
  nmap gx <Plug>(openbrowser-smart_search)
  vmap gx <Plug>(openbrowser-smart_search)
'''

[[plugins]]
repo = 'kannokanno/previm'

# text browser
[[plugins]]
repo = 'yuratomo/w3m.vim'
if = '''executable("w3m")'''

###
# syntax check
###
[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = '''
  let g:syntastic_mode_map = {
        \ 'mode': 'passive',
        \ 'active_filetypes': ['swift']
        \}
'''

###
# editor
###
[[plugins]]
repo = 'editorconfig/editorconfig-vim'

###
# status line
###
[[plugins]] # status line
repo = 'itchyny/lightline.vim'
depends = ['itchyny/vim-gitbranch']
hook_add = '''
  function! LightLineFileName()
    return expand('%') !=# '' ? expand('%') : '[No Name]'
  endfunction

  let g:lightline = {
        \ 'colorscheme': 'powerline',
        \ 'active': {
        \   'left': [ ['mode', 'paste'],
        \             ['gitbranch', 'readonly', 'filename', 'modified'] ]
        \ },
        \ 'component_function': {
        \   'gitbranch': 'gitbranch#name',
        \   'filename': 'LightLineFileName'
        \ },
        \}
'''

[[plugins]]
repo = 'itchyny/vim-gitbranch'

###
# colorscheme
###
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  augroup set_colorscheme
    autocmd!
    autocmd VimEnter * nested syntax on
    autocmd VimEnter * nested colorscheme iceberg
  augroup END
'''
